[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3 --log-format defmt"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[env]
DEFMT_LOG="info"

[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
