name: POV SIM CI

on:
  push:
    tags:
      - "pov-sim/v*"

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build the executable
        working-directory: tools/pov-sim
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build the dist folder
        working-directory: tools/pov-sim
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-gnu/release/pov-sim dist/pov-sim
          cp images.json dist
          cp -r images dist/

      - name: Package binary
        working-directory: tools/pov-sim
        run: tar -czvf pov-sim-linux-x86_64.tar.gz -C dist pov-sim images.json images

      - name: Upload release binaries
        uses: actions/upload-artifact@v7
        with:
          name: pov-sim-linux-x86_64.tar.gz
          path: tools/pov-sim/pov-sim-linux-x86_64.tar.gz

  macos:
    runs-on: macos-latest
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build the executable
        working-directory: tools/pov-sim
        run: cargo build --release --target x86_64-apple-darwin --target aarch64-apple-darwin

      - name: Build the dist folder
        working-directory: tools/pov-sim
        run: |
          mkdir dist
          cp images.json dist
          cp -r images dist/

      - name: Create a fat executable
        working-directory: tools/pov-sim
        run: lipo -create -output dist/pov-sim target/x86_64-apple-darwin/release/pov-sim target/aarch64-apple-darwin/release/pov-sim

      - name: Package binary
        working-directory: tools/pov-sim
        run: |
          tar -czvf pov-sim-macos.tar.gz -C dist pov-sim images images.json

      - name: Upload release binaries
        uses: actions/upload-artifact@v7
        with:
          name: pov-sim-macos.tar.gz
          path: tools/pov-sim/pov-sim-macos.tar.gz

  windows:
    runs-on: windows-latest
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build the executable
        working-directory: tools/pov-sim
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Build the dist folder
        working-directory: tools/pov-sim
        shell: pwsh
        run: |
          New-Item -Name dist -ItemType Directory
          Copy-Item images.json dist -Force
          Copy-Item images dist -Recurse -Force

      - name: Package binary
        working-directory: tools/pov-sim
        shell: pwsh
        run: Compress-Archive -Path dist\* -DestinationPath pov-sim-windows.zip -Force

      - name: Upload release binaries
        uses: actions/upload-artifact@v7
        with:
          name: pov-sim-windows.zip
          path: tools/pov-sim/pov-sim-windows.zip

  release:
    name: Publish release
    needs: [macos, linux, windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: release-artifacts
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: release-artifacts/*
